version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile-php-${PHP_VERSION:-8.3}
        ports:
            - "9020:80"
        volumes:
            - ./tests:/usr/share/nginx/html/tests
            - ./src:/usr/share/nginx/html/src